### ISSUE TITLE
Unisintall fail

### ISSUE THREAD

**Issue by Cleboost** [Zinidia/Pelinstaller#1]
If we want to delete fail install, the uninstall crash

![image](https://github.com/pelican-installer/pelican-installer/assets/61158869/40b35a97-2bc8-43d6-9621-387bdb21c867)

**Comment by Zinidia** [comment]
Thank you for your report, unfortunately the uninstallation script is designed to only uninstall Pelican if it was properly installed, it cannot uninstall your instance because the Nginx webserver config is missing. I'm currently overhauling the uninstallation script in the compose rewrite to account for this issue.
