### ISSUE TITLE
eggs

### ISSUE THREAD

**Issue by jaimy1999** [Zinidia/Pelinstaller#3]
i can't upload eggs i get this error
![Schermafbeelding 2024-09-14 212850](https://github.com/user-attachments/assets/9efb0d89-ca94-407e-a76c-1561c6b2bbed)

**Comment by Zinidia** [comment]
Hi, thanks for beinging this to our attention, there was an nginx permission issue which I have since fixed. There's currently an issue on Pelican's side but we added a temporary patch on our end.

To fix this for your install, you can run `chown -R www-data:www-data /var/www/pelican`, please see https://pelican.dev/docs/troubleshooting/ for more details.
